### ISSUE TITLE
[Bug] CSRF Validation broken since 2.0.0

### ISSUE THREAD

**Issue by DevYukine** [Fallenbagel/jellyseerr#1011]
### Description

i Have CSRF Protection enabled and my Jellyseerr behind reverse proxy, after upgrading to 2.0.0 every request fails with 

`{
    "message": "invalid csrf token"
}`

and the http status code 403, this only started happening after upgrading to 2.0.0

### Version

2.0.0

### Steps to Reproduce

1. Enable CSRF-Protection
2. Make sure you have version 2.0.0 running
3. Try to request anything or save the settings

### Platform

desktop

### Device

Windows

### Operating System

Windows 11

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by r0astch1ck3n** [comment]
Same issue here. It can be worked around by editing settings.json and changing:
"csrfProtection" from true to false.

Docker running as:

`docker run -d  --name jellyseerr  -e LOG_LEVEL=debug  -e TZ=Europe/London  -p 5055:5055  -v /opt/jellyseerr/appdata/config:/app/config  --restart unless-stopped  fallenbagel/jellyseerr:latest
`
With caddy running a reverse proxy:

`reverse_proxy localhost:5055`

**Comment by Fallenbagel** [comment]
If you have csrfProtection enabled you cannot use jellyseerr through http

**Comment by osh123** [comment]
Same here, running via HTTPS, CSRF verification is failing.

**Comment by M0NsTeRRR** [comment]
Hello,

For now, you can disable CSRF validation if you wish to remain on version 2.0.0 (be aware of the CSRF attack risks). Otherwise, you can roll back to version 1.9.2. I've investigated the issue with @Fallenbagel and identified the cause.

The issue originates from [this PR](https://github.com/Fallenbagel/jellyseerr/pull/840). Axios automatically sets the `XSRF-TOKEN`, but `fetch` does not. A PR is currently a work in progress, and the fix is already known — just a bit more waiting is required :)
