### ISSUE TITLE
Anime Series Type setting not applied correctly when sending request to Sonarr

### ISSUE THREAD

**Issue by Turik1** [Fallenbagel/jellyseerr#1065]
### Description

I’m encountering an issue with the "Anime Series Type" setting in Jellyseerr. Despite selecting "Standard" in the settings, Jellyseerr still sends requests to Sonarr with the series type as "Anime." This results in Sonarr treating the series as anime, which is not the intended behavior.

### Version

2.0.1

### Steps to Reproduce

1. Go to Sonarr Settings in Jellyseerr.
2. Under Anime Series Type, select Standard.
3. Save the settings.
4. Make a request for an anime series that should be sent as "Standard" to Sonarr.
5. Check Sonarr and observe that the series type is set as "Anime" instead of "Standard."

### Platform

desktop

### Device

Server

### Operating System

Debian / Docker-Image fallenbagel/jellyseerr:develop

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by lattaai1** [comment]
Hello, I tried to fix the issue

This is what I did:
I have identified the issue in the `addSeries` method of the `SonarrAPI` class. The `seriesType` parameter was not being properly set when adding a new series to Sonarr. I've modified the code to use the `options.seriesType` value when creating a new series, which should resolve the issue of series always being set as 'Anime' regardless of the selected option in Jellyseerr.

I also created pull request: https://github.com/Fallenbagel/jellyseerr/pull/1066


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
> 
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.**

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by Fallenbagel** [comment]
You need to press test in sonarr. Then select anime absolute and then back to standard again
