### ISSUE TITLE
Prowlarr support

### ISSUE THREAD

**Issue by sunjam** [Fallenbagel/jellyseerr#174]
### Description

Related to #96 and #134.  [Prowlarr](https://github.com/Prowlarr/Prowlarr) `is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports management of both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Lidarr, Mylar3, Radarr, Readarr, and Sonarr offering complete management of your indexers with no per app Indexer setup required (we do it all).`

### Desired Behavior

Prowlarr simplifies integration by serving as a proxy and manager for almost all existing *rr services, including those you currently support + those on your road map.

Thanks for considering either way!

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
I'm not sure why you'd need prowlarr support on a request management software, could you care to explain more so I understand? 🤔

**Comment by teambvd** [comment]
For my own .02 - this is a lower priority 'nice-to-have'. The only difference this would make to the end user is saving them about 5 minutes during setup (one endpoing to connect to vs however many they're using), and a few additional minutes each time they make a change to one of their media management applications configuration (which should be a super rare occurrence).

It'd be kinda neat to have, I'd like it - I'd just prefer many other features be integrated prior, personally.

**Comment by Fallenbagel** [comment]
I'm still a little confused on the prowlarr support for request management because wouldn't just the sonarr and radarr need the indexers because they will be doing the indexing and sending releases to the download client? 🤔

**Comment by Continous** [comment]
> I'm still a little confused on the prowlarr support for request management because wouldn't just the sonarr and radarr need the indexers because they will be doing the indexing and sending releases to the download client? 🤔

I think the idea is that the user already has sonarr/radarr set up through prowlarr, and instead wants jellyseerr to communicate to prowlarr instead of directly to sonarr/radarr. Perhaps too, the user may wish to use a service provided by prowlarr not supported directly by jellyseer, and so prowlarr can handle things, such as may be the case for music/audio where jellyseerr doesn't yet support a music/audio indexer.

**Comment by gauthier-th** [comment]
I don't think this will be implemented. It would be a lot of work and a whole refactor of the app to avoid 5min of setup.

**Comment by Neurology0443** [comment]
I know this is already closed, but there is more to it than avoid 5min of setup. Sonarr has some big flaws when it comes to media management other than English releases on non-English trackers. Sonarr, based on TVDB, sometimes can't find a release because it hasn't the alternative name for that release in another language or because it just doesn't exist because it's not a native English release. This breaks the whole automation setup for non-English releases.

However, Prowlarr can find any release name on any indexer because it's based on regex and not on a metadata provider. But I guess this won't happen any time soon, just wanted to add another reason why Prowlarr support would be a great addition :).
