### ISSUE TITLE
Some shows are found in Sonarr search but not Jellyseerr search

### ISSUE THREAD

**Issue by erdemoney** [Fallenbagel/jellyseerr#233]
### Description

I'm not sure how the search works for jellyseerr but I assume it should mirror results from sonarr. However some shows that are found in the sonarr search, such as Malcom in the Middle are not found on Jellyseerr's search.

### Version

1.1.1

### Steps to Reproduce

1. search tv show name

### Screenshots

![Screen Shot 2022-10-10 at 9 03 49 PM](https://user-images.githubusercontent.com/21229271/194994649-38f5e329-ca99-4c49-87d3-9b2286987171.png)

### Platform

desktop

### Device

Web

### Operating System

MacOS

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
It does not mirror sonarr search. It uses tmdb. This could be due to the tmdb api missing to hit (on latest this is an issue, which has been fixed I'll release new version tonight, meanwhile try the develop)

![Screenshot_20221011-132123_Chrome.jpg](https://user-images.githubusercontent.com/98979876/195037729-71f80616-7712-4ecb-9b30-93766b471cc8.jpg)

**Comment by erdemoney** [comment]
Okay thanks!

**Comment by erdemoney** [comment]
Okay thanks!
