### ISSUE TITLE
Jellyfin user import show no profile pictures

### ISSUE THREAD

**Issue by butts136** [Fallenbagel/jellyseerr#237]
### Description

Jellyfin users import.

No profiles pictures are imported, they are shown as broken link

Thanks

### Version

1.2.0

### Steps to Reproduce

No need to explain

### Screenshots

![image](https://user-images.githubusercontent.com/65697898/195435132-888f935c-818d-45d2-a109-e4de6cbe56e8.png)

### Platform

desktop

### Device

Windows 11

### Operating System

Linux

### Browser

Opera GX

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Did you add the external hostname? You'll have to go to settings > jellyfin and add the externalhostname

**Comment by Fallenbagel** [comment]
This will be fixed in 1.2.1. It seems the last PR messed it up

**Comment by Fallenbagel** [comment]
@Smexhy Hi. Could you test if `:develop` works for you? I have no means of testing base paths, could you check if it works now?

**Comment by Fallenbagel** [comment]
> Hey, after relogging all users, their profile picture now loads perfectly fine, thank you!

Thank you so much for the feedback! I'll make 1.2.1 release tonight

**Comment by GlassedSilver** [comment]
Just wanna add to this for anyone who finds themselves in my situation as well where they at one point decided to make their Jellyfin user a local account in Jellyseerr sign-in:

You have to log out and log in that user using their associated Jellyfin identity. Then you should see the profile picture come up fine and stay intact once you log out and go back to using your Jellyseerr account credentials again. Rinse and repeat for any affected user.

**Comment by caioolivv** [comment]
I'm having the same problem again, but the cause seems to be different. Jellyseerr tries to fetch the image with the URL `https://hostname/Users/0b911f2430ad4cbc8e32a7080491f466/Images/Primary/\?tag\=45173acd8f7a867d947489373eb3af90\&quality\=90` while the right URL is `https://jellyfin.azeitonas.xyz/Users/0b911f2430ad4cbc8e32a7080491f466/Images/Primary/?tag\=45173acd8f7a867d947489373eb3af90\&quality\=90`. Notice there's an extra backslash before `?tag`.

**Comment by caioolivv** [comment]
I'm having the same problem again, but the cause seems to be different. Jellyseerr tries to fetch the image with the URL `https://hostname/Users/0b911f2430ad4cbc8e32a7080491f466/Images/Primary/\?tag\=45173acd8f7a867d947489373eb3af90\&quality\=90` while the right URL is `https://hostname/Users/0b911f2430ad4cbc8e32a7080491f466/Images/Primary/?tag\=45173acd8f7a867d947489373eb3af90\&quality\=90`. Notice there's an extra backslash before `?tag`.

**Comment by Fallenbagel** [comment]
> I'm having the same problem again, but the cause seems to be different. Jellyseerr tries to fetch the image with the URL `https://hostname/Users/0b911f2430ad4cbc8e32a7080491f466/Images/Primary/\?tag\=45173acd8f7a867d947489373eb3af90\&quality\=90` while the right URL is `https://hostname/Users/0b911f2430ad4cbc8e32a7080491f466/Images/Primary/?tag\=45173acd8f7a867d947489373eb3af90\&quality\=90`. Notice there's an extra backslash before `?tag`.

https://github.com/Fallenbagel/jellyseerr/blob/main/server/routes/auth.ts#L285

As you can see there is no extra backslash in the code itself. So looks like a misconfiguration issue (something somewhere is interfering possibly the reverse proxy).

Can you hop onto discord so we can troubleshoot
