### ISSUE TITLE
系列里的电影都显示为可以申请需求的

### ISSUE THREAD

**Issue by sy911212** [Fallenbagel/jellyseerr#346]
### Description

系列里的电影都显示为可以申请需求的，但是实际电影已经早就下载完了，在Jellyseerr中仍被标记为为下载的，
剧集和单部电影都可以正常显示。

### Desired Behavior

希望能修复下这个问题。

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Does it work if you manually press jellyfin full scan?

[Google translated]
手动按jellyfin full scan 有用吗？

**Comment by sy911212** [comment]
已经试过了，没有效果，只要是被归在系列里的电影，虽然下载了，但还是会显示为需要下载。

**Comment by Fallenbagel** [comment]
> 已经试过了，没有效果，只要是被归在系列里的电影，虽然下载了，但还是会显示为需要下载。

That does sound like a tmdbID error. Best thing to try is moving the movie out of jellyfin, removing any metadata and then bring it back in. Let it scan. Let jellyseerr scan too. See if that works. Also please share logs.

[Google Translated]
这听起来像是一个 tmdbID 错误。最好的尝试是将电影从 jellyfin 中移出，删除所有元数据，然后将其放回原处。让它扫描。让 jellyseerr 也扫描。看看是否有效。也请分享日志。

**Comment by sy911212** [comment]
我研究了下，要是在使用jellyseerr后下载的电影，然后形成的系列，就不会出现这个问题，但是jellyseerr无法扫描到原来生成系列的电影，希望能改进下这一点，要不然每次都是从系列拿出再扫描会很麻烦，谢谢1

**Comment by sy911212** [comment]
还有个问题，jellyseerr的中文显示只有部分可以成功，还有一部分显示的还是英文，看着很不美观和协调，还请更新一下语音，谢谢！

**Comment by Fallenbagel** [comment]
> 我研究了下，要是在使用jellyseerr后下载的电影，然后形成的系列，就不会出现这个问题，但是jellyseerr无法扫描到原来生成系列的电影，希望能改进下这一点，要不然每次都是从系列拿出再扫描会很麻烦，谢谢1

About this, the reason why it can't detect the movies before jellyseerr is because you're missing the tmdb ID. You'll need to refresh and replace the metadata of all your files. You can use sonarr/radarr for that and a naming scheme that includes the `[tvdbid-xxxxx]` so for example `Wednesday (2023) [tvdbid-48382]` or for movies `[imdbid-ttxxxxxxx]`. The reason is because jellyseerr uses tmdbid to match the series and movies and if it's missing in your metadata there's really nothing it can do until you refresh metadata and replace it.

[Google translated]
关于这一点，它无法检测到 jellyseerr 之前的电影的原因是因为您缺少 tmdb ID。您需要刷新并替换所有文件的元数据。您可以为此使用 sonarr/radarr 以及包含 `[tvdbid-xxxxx]` 的命名方案，例如 `Wednesday (2023) [tvdbid-48382]` 或电影 `[imdbid-ttxxxxxxx]`。原因是因为 jellyseerr 使用 tmdbid 来匹配系列和电影，如果它在您的元数据中丢失，那么在您刷新元数据并替换它之前它真的无能为力。

> 还有个问题，jellyseerr的中文显示只有部分可以成功，还有一部分显示的还是英文，看着很不美观和协调，还请更新一下语音，谢谢！

The reason why some Chinese translations aren't finished is because there have not been contributions for it. I do not know Chinese so I cannot update the translations myself 😔

[Google translate]
有些中文翻译没有完成的原因是没有人投稿。我不懂中文所以我不能自己更新翻译😔

**Comment by sy911212** [comment]
> 



> > 我研究了下，要是在使用jellyseerr后下载的电影，然后形成的系列，就不会出现这个问题，但是jellyseerr无法扫描到原来生成系列的电影，希望能改进下这一点，要不然每次都是从系列拿出再扫描会很麻烦，谢谢1
> 
> 关于这一点，它无法在 jellyseerr 之前检测到电影的原因是因为您缺少 tmdb ID。您需要刷新并替换所有文件的元数据。您可以为此使用声纳/雷达器，以及包含 so 例如或电影的命名方案。原因是因为 jellyseerr 使用 tmdbid 来匹配系列和电影，如果元数据中缺少它，那么在您刷新元数据并替换它之前，它实际上无能为力。`[tvdbid-xxxxx]``Wednesday (2023) [tvdbid-48382]``[imdbid-ttxxxxxxx]`
> 
> [谷歌翻译] 关于这一点，它无法检测到 jellyseerr 之前的电影的原因是因为您缺少 tmdb ID。您需要刷新并替换所有文件的元数据。您可以为此使用 sonarr/radarr 以及包含 的命名方案，例如 或电影 。原因是因为 jellyseerr 使用 tmdbid 来匹配系列和电影，如果它在您的元数据中丢失，那么在您刷新元数据并替换它之前它真的无能为力。`[tvdbid-xxxxx]``Wednesday (2023) [tvdbid-48382]``[imdbid-ttxxxxxxx]`
> 
> > 还有个问题，jellyseerr的中文显示只有部分可以成功，还有一部分显示的还是英文，看着很不美观和协调，还请更新一下语音，谢谢！
> 
> 有些中文译本之所以没有完成，是因为没有这方面的贡献。我不懂中文，所以我不能自己更新翻译😔
> 
> [谷歌翻译] 有些中文翻译没有完成的原因是没有人投稿。我不懂中文所以我不能自己更新翻译😔


元数据是jellyfin通过The Movie Database (TMDB)削刮的也是包括ID的，我之所以不用radarr削刮是因为没法削刮中文海报，所以这边是否能加入支持The Movie Database (TMDB)的ID支持。

**Comment by Fallenbagel** [comment]
I didn't mean to scrape with radarr. I meant just add the tmdbid into the series folder name and refresh and replace metadata through jellyfin. It should fix your issues.

我不是故意用 radarr 刮擦的。我的意思是只需将 tmdbid 添加到系列文件夹名称中，然后通过 jellyfin 刷新和替换元数据。它应该可以解决您的问题。

**Comment by sy911212** [comment]
![image](https://user-images.githubusercontent.com/126683328/226627781-1411fd82-e554-43d4-be83-3a6f150d4e7f.png)
上面截图是我的一部在系列里的电影元数据，您这边说的ID也是都有的。

**Comment by Fallenbagel** [comment]
I know. I meant to add TMDBID to the series folder name. The do a library scan. Sometimes jellyfin messes up metadata and even if the tmdb ID is there to be seen if the initial generation had it missing this issue will occur. Which is why we are adding the tmdbid to the series folder name so it looks like for example `Wednesday (2023) [tmdbid-63627]` for the series name.

我知道。我的意思是将 TMDBID 添加到系列文件夹名称中。进行库扫描。有时 jellyfin 会弄乱元数据，即使可以看到 tmdb ID 是否在初始生成中丢失，也会出现此问题。这就是我们将 tmdbid 添加到系列文件夹名称的原因，因此系列名称看起来像“Wednesday (2023) [tmdbid-63627]”

**Comment by sy911212** [comment]
我看了下您可以能理解的系列和我理解的不一样，我说的系列是电影的合集，例如下面的截图：
![image](https://user-images.githubusercontent.com/126683328/226632637-33205bcf-f3a9-4a9a-83d5-e1c635772803.png)
合集会把相同的电影续集都放在一个合集里面例如下面这种：
![image](https://user-images.githubusercontent.com/126683328/226633283-4f844aa3-cc73-4eec-88d4-34924268fcbd.png)
但是在合集里面的电影不会被Jellyseerr所识别

**Comment by Fallenbagel** [comment]
Oh yes I understand now. Sorry, I do not know chinese so I am using google translate to translate. For movies you add the `imdbid-ttxxxxx` to the name of the movie file so for example "Alien³ (1992) [imdb-tt0103644].mkv`.

哦，是的，我现在明白了。对不起，我不懂中文所以我用谷歌翻译来翻译。对于电影，您将 `imdbid-ttxxxxx` 添加到电影文件的名称中，例如“Alien³ (1992) [imdb-tt0103644].mkv`。

![Screenshot_20230321_194209_Termux](https://user-images.githubusercontent.com/98979876/226641889-7d1bde8b-d730-4dea-b53c-2a2203f1ac06.jpg)

Also make sure you turned on this in your jellyseerr settings > jellyfin > Libraries
还要确保您在 jellyseerr 设置 > jellyfin > 库中打开了它

![Screenshot_20230321_193547_Chrome Dev](https://user-images.githubusercontent.com/98979876/226642167-3a196ea0-9226-4588-b597-b19629931dd5.jpg)

**Comment by sy911212** [comment]
好的非常感谢您的帮助！
