### ISSUE TITLE
Click Jellyfin to play, can't jump correctly

### ISSUE THREAD

**Issue by 13001311828** [Fallenbagel/jellyseerr#38]
Click to play on jellyfin on the jellyseerr interface, the jump link is missing a part, for example:
wrong：http://192.168.x.x:8096/web/#!/details?id=xxxxxx
right：http://192.168.x.x:8096/web/index.html#!/details?id=xxxx

Hope this can be fixed in the next version

**Comment by Fallenbagel** [comment]
Hi. That is because the current one is made for jellyfin 10.8.0. 

The url link is handled differently for both 10.7.7 and 10.8.0, and given that 10.8.0 is just around the corner(with a lot of people using it as production including me[running `10.8.0-beta1` and loving it), therefore, the play on jellyfin redirects to the jellyfin 10.8.0 url version. The develop version is also using the jellyfin 10.8.0 url version of redirection.

**Comment by 13001311828** [comment]
Thank you for your reply, I look forward to the follow-up development
