### ISSUE TITLE
Manage panel in PWA is hard to close

### ISSUE THREAD

**Issue by ioqy** [Fallenbagel/jellyseerr#462]
### Description

The "Manage Movie" and "Manage Series" panel is too tall in the PWA on iOS and reaches into the upper area reserved by the OS for sliding down the control panel. So when hitting the "X" with your finger you don't click the "X" but hit the area for sliding down the control panel.

### Version

1.6.0

### Steps to Reproduce

1. Open any "Manage" panel in the PWA on iOS

### Screenshots

The red line is the approximate border between the PWA and the area used to slide down the control panel.

![image](https://github.com/Fallenbagel/jellyseerr/assets/95605581/6467d6c4-9644-4d89-b7ab-53427e37a1df)

### Platform

smartphone

### Device

iPhone XS

### Operating System

iOS 16.6

### Browser

Safari

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
![Screenshot_20240523_164329_Chrome Dev.jpg](https://github.com/Fallenbagel/jellyseerr/assets/98979876/be582887-c381-401a-97c6-3969fde8c521)

This has been fixed in recent versions and I have not been able to reproduce this so I will be closing this. Feel free to re-open if you still face the same issue
