### ISSUE TITLE
Entity Metadata Not Found Error

### ISSUE THREAD

**Issue by JaiSehgal** [Fallenbagel/jellyseerr#478]
### Description

OS - Windows 11
Jellyseerr Version - v1.7.0

Upon running "yarn start" after installing, I get the following error : 

"2023-09-14T06:38:30.097Z [error]: EntityMetadataNotFoundError: No metadata for "User" was found.
    at DataSource.getMetadata (C:\Users\Username\jellyseerr-1.7.0\node_modules\typeorm\data-source\DataSource.js:295:19)
    at get metadata [as metadata] (C:\Users\Username\jellyseerr-1.7.0\node_modules\typeorm\repository\Repository.js:15:40)
    at Repository.count (C:\Users\Username\jellyseerr-1.7.0\node_modules\typeorm\repository\Repository.js:160:40)
    at C:\Users\Username\jellyseerr-1.7.0\dist\index.js:112:45
Note: This command was run via npm module 'win-node-env'
error Command failed with exit code 1."

I was facing the same issue with v1.6.0, although downgrading to v1.5.0 fixed it for me. I was hoping to get a fix with the new update, but unfortunately I'm in the same situation as I was with the previous build.

I'd appreciate any help I can get.

PS - I do not know a thing about developing code, all I do is follow installation instructions. Please give me steps to typescript related fixes if possible. Thanks in advance!

### Version

1.7.0

### Steps to Reproduce

1. Extract the source code in C:/Users/Username
2. Open CMD in the extracted folder
3. Run commands (sequentially)
     npm i -g win-node-env
     yarn install
     yarn run build
     yarn start

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser

Firefox

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
oh yeah i forgot to mention. On windows you have to downgrade typeorm version. I added it as an announcement to discord and forgot to add it to github readme. Its a bug with the latest typeorm version so windows user will have to do:
> Before you `yarn build` please downgrade your typeorm version by `yarn add typeorm@0.3.11`

**Comment by blibdoolpoolp** [comment]
I followed all of the instructions here, I downgraded it just like instructed, and still getting the error. This is my only app I need a Linux VM for :'( I just want it on Windows...

**Comment by Fallenbagel** [comment]
> I followed all of the instructions here, I downgraded it just like instructed, and still getting the error. This is my only app I need a Linux VM for :'( I just want it on Windows...

Did you after downgrade rebuild it?

**Comment by blibdoolpoolp** [comment]
Okay, so here's the thing. I think I got it to work, but it just completed the commands right before I had to go to work so I didn't get to see the complete outcome and if like the web page actually loaded or not. But I think it would be helpful for users to specify when exactly they should run the yarn add command. I did it the first time before I ran any of the commands in the code block to build the program. I installed node, I installed yarn, and then I ran the yarn add command. Then I ran the four commands in the code block, and it failed. Notably, it gave me many many errors when id do the first yarn install command both times, saying unmet dependencies. Anyways, the second time I ran I think the first two commands but then right before I did the yarn build command, that's when I downgraded, and I think that's when it worked. But I'm still not positive it worked, it just didn't give me as many errors when I did the yarn run command, and I think at the end it looked like it ran the server, at least on the command line output. I had to go to work though and I forgot what port it was supposed to be on and I didn't have time to look it up lol. If that is actually the place you're supposed to run it, I definitely got really lucky, because I've never used either of these apps before.

**Comment by Fallenbagel** [comment]
I did specify where. I specified where exactly to run yarn add which was inbetween yarn install and yarn build. Its due to a bug in the package itself that we have to resort to this. And using the advanced build from source method is not recommended for most users.

And also when you run yarn install THOSE ARE NOT ERRORS. That's expected. This is how node packages work. Those are warnings. And doesn't matter.

**Comment by blibdoolpoolp** [comment]
Okay, so I had it running for about two days. Thank you for the explanation. I thought the "yarn build" just referred to the entire code block. I apologize. But now, I restarted my PC, and it exploded. I rebuilded it and everything, even though I thought we just run yarn start again, and it still gives me this. 

`λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)

warning ..\..\package.json: No license field
$ tsc --project server/tsconfig.json && copyfiles -u 2 server/templates/**/*.{html,pug} dist/templates && tsc-alias -p server/tsconfig.json
Done in 134.17s.
PS C:\Users\blibd\jseer\jellyseerr> yarn start
yarn run v1.22.19
warning ..\..\package.json: No license field
$ NODE_ENV=production node dist/index.js
2023-11-12T19:51:14.318Z [info]: Starting Overseerr version develop-local
warn  - You have enabled experimental features (scrollRestoration, largePageDataBytes) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

2023-11-12T19:51:18.358Z [error]: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Settings.load (C:\Users\blibd\jseer\jellyseerr\dist\lib\settings.js:332:61)
    at C:\Users\blibd\jseer\jellyseerr\dist\index.js:80:52
Note: This command was run via npm module 'win-node-env'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\blibd\jseer\jellyseerr>`

**Comment by Fallenbagel** [comment]
Your settings.json file is corrupted. There's an unexpected character in the top. This is not related to this issue.

Could you jump into discord so I could help you fix that as we carry out our support there mostly.

**Comment by blibdoolpoolp** [comment]
Sure thing, I'm about to eat lunch and then I'll hop on. Thank you for your hard work on this.

**Comment by Danish-H** [comment]
I think it is an intended change, please see the second point from [here](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#deprecations):
> entities, migrations, subscribers options inside DataSourceOptions accepting string directories support is deprecated. You'll be only able to pass entity references in the future versions.

I had some luck building without downgrading typeorm, after importing each of the entities individually and passing them as described in [this response](https://github.com/typeorm/typeorm/issues/9766#issuecomment-1761788033)

What's your view on this?

**Comment by Fallenbagel** [comment]
> I had some luck building without downgrading typeorm, after importing each of the entities individually and passing them as described in [this response](https://github.com/typeorm/typeorm/issues/9766#issuecomment-1761788033)

Oh. I was initially following [comment](https://github.com/typeorm/typeorm/issues/9860#issuecomment-1487566940) with the downgrade

**Comment by Fallenbagel** [comment]
> I think it is an intended change, please see the second point from [here](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#deprecations):
> > entities, migrations, subscribers options inside DataSourceOptions accepting string directories support is deprecated. You'll be only able to pass entity references in the future versions.

What I don't understand is, since they're deprecated how come it works on Unix based OSes without downgrading or manually importing each entities and passing them 🤔

**Comment by Danish-H** [comment]
> > I think it is an intended change, please see the second point from [here](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#deprecations):
> > > entities, migrations, subscribers options inside DataSourceOptions accepting string directories support is deprecated. You'll be only able to pass entity references in the future versions.
> 
> What I don't understand is, since they're deprecated how come it works on Unix based OSes without downgrading or manually importing each entities and passing them 🤔

You're completely right, that's really weird.. Could it be that maybe they had some 'extra code' to account for the different backslash convention for Windows paths, and they only removed specifically this part, leaving the rest of the support to be removed in "future versions"?

But either way, do you think this is a non-issue, or a PR should be made to resolve this?

Considering the large number of imports it would require especially for migrations, I was thinking we could have a script that is run on build/compile which goes through the relevant folders and creates an index file, so that they can all be imported as constant arrays in one reusable line in the main file

**Comment by Fallenbagel** [comment]
> But either way, do you think this is a non-issue, or a PR should be made to resolve this?
> 
> Considering the large number of imports it would require especially for migrations, I was thinking we could have a script that is run on build/compile which goes through the relevant folders and creates an index file, so that they can all be imported as constant arrays in one reusable line in the main file

We should fix this properly with a pr. For now i added a postinstall script and once we properly fix this by importing the entities, we can close this issue and remove postinstall script :)
