### ISSUE TITLE
options to request missing episodes in a "partially available" TV series

### ISSUE THREAD

**Issue by ChrisAnon** [Fallenbagel/jellyseerr#592]
### Description

Hello, I just installed jellyseerr to play around with and it appears to be missing a feature I was hoping to have or I am not seeing any option for it.

Is it possible to add (hopefully it's there and I am missing something) options to be able to display and request any missing TV episodes that are within the "partially available" seasons? IE to have the same options as missing seasons in a series for missing episodes in the season?    

### Desired Behavior

Have the same options as the "season picker" for series but at the episode level for seasons without having to delete and request the entire season

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Episode request is a planned feature (upstream too) and duplicate issue of #264

The reason it's kinda hard to implement is because sonarr and tmdb disagree on episode numbering sometimes especially on old series

**Comment by Silverbullet069** [comment]
Now I understand. In Sonarr, you have 2 checkboxes called "Start search for missing episodes" and "Start search for cutoff unmet episodes". But I didn't see any options like that in Jellyseerr's Settings > Service > Sonarr settings. That's why Uzumaki already got 2 episodes but Sonarr didn't auto download them :v
