### ISSUE TITLE
Provide .deb packages

### ISSUE THREAD

**Issue by ilovethensa** [Fallenbagel/jellyseerr#697]
### Description

Would make installing on docker-less environments way easier

### Desired Behavior

Provided .deb files

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by joshuaboniface** [comment]
Agreed, willing to take this on.

**Comment by joshuaboniface** [comment]
So, Debian packaging here is going to be quite difficult to do "properly", as splitting the various parts out into Debianlized folders seems to be impossible.

I can do a hacky alternative though of putting everything under `/opt/jellyseerr`, which isn't quite as nice (and wouldn't be accepted to an upstream) but will work for now.

**Comment by joshuaboniface** [comment]
That is possible, but I don't think it's good practice to do so.

**Comment by joshuaboniface** [comment]
The other issue would be packaging the `node_modules` in the `.deb` which makes it *huge*. I'm trying to see if there's a way around that but I'll need to do some more reading into how to properly package NodeJS projects in Debian.

**Comment by joshuaboniface** [comment]
Just for context: the big difference between a `.deb` and the AUR is that AUR packages are built on the client machine at install, while `.deb`s are built remotely and the full binaries are sent. This is running into problems with `node_modules` because it tries to do a lot of `.deb` magic on them and fails. So there has to be a better way here, but I'm also thinking that this might not be entirely possible, at least not in a clean way that won't result in a 500+MB `.deb`.

**Comment by Fallenbagel** [comment]
> Just for context: the big difference between a `.deb` and the AUR is that AUR packages are built on the client machine at install, while `.deb`s are built remotely and the full binaries are sent. This is running into problems with `node_modules` because it tries to do a lot of `.deb` magic on them and fails. So there has to be a better way here, but I'm also thinking that this might not be entirely possible, at least not in a clean way that won't result in a 1.6+GB(!) `.deb`.

I guess at that point and install script would be better then? 🤔

**Comment by joshuaboniface** [comment]
I've done some more digging, and for simple NodeJS projects, https://github.com/heartsucker/node-deb seems like a good solution. But from what I've seen of it Overseerr (and hence Jellyseerr) is not simple. Most of all, the fact that the `node_modules` dir is over 1.6GB pretty much precludes making a sensible `.deb` here, as that entire thing needs to be included. We just don't have the AUR benefit of running things like `yarn build` at install time.

So I definitely think an installer script is the better bet here.

**Comment by nsauter** [comment]
Agreed that maybe the .deb Package is too much work. But is there a possibility, to provide like a build binary or something? Im that person who hates having npm, pnpm and that node stuff on his servers because they bloat everything up and make it hard to have a 'clean' workspace.

**Comment by gauthier-th** [comment]
That's the point of the Docker imageLe 24 oct. 2024 19:19, Nico Sauter ***@***.***> a écrit :
Agreed that maybe the .deb Package is too much work. But is there a possibility, to provide like a build binary or something? Im that person who hates having npm, pnpm and that node stuff on his servers because they bloat everything up and make it hard to have a 'clean' workspace.

**Comment by nsauter** [comment]
Docker doesnt make things better. Maybe even worse in my opinion.

**Comment by Fallenbagel** [comment]
> Docker doesnt make things better. Maybe even worse in my opinion.

This is not a conventional app but a web app. Creating a binary is not as easy as it might seem. Not even sure how feasible it is to do so. 

If you do find a way to do so, feel free to open a pr though :)
