### ISSUE TITLE
Request series fails: sonarr not setup

### ISSUE THREAD

**Issue by mo-st** [Fallenbagel/jellyseerr#699]
### Description

I use Jellyseerr without Sonarr or Radarr. A request for "Adventure Time: Distant Lands" (.../tv/94810) fails with the message: We were unable to find a match for this series. In the logs, the Error says that Sonarr has not been setup, which is true of course but I was under the impression sonarr is optional. Is Sonarr mandatory for certain series, as so far other series worked fine. I read similar issues with failed linking to tmdb but I checked all of the links and they seem to work just fine. 

### Version

1.7.0

### Steps to Reproduce

1. Go to `[jellyseerr-URL]/tv/94810`
2. Click "request"
3. See error

### Logs

```shell
2024-03-29T17:11:31.215Z [error][Media Request]: No sonarr server has been setup
```

### Platform

smartphone

### Device

Pixel 8

### Operating System

Android 14

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
The issue is the tv series you're requesting does not exist in tvdb. That's why. They removed it and added it to adventure times special

**Comment by mo-st** [comment]
Thank you for your quick reply. I'm not familiar with the inner workings of this, so can I do something about this to fix it? Like contributing to tvdb or jellyseerr?

**Comment by Fallenbagel** [comment]
> Thank you for your quick reply. I'm not familiar with the inner workings of this, so can I do something about this to fix it? Like contributing to tvdb or jellyseerr? 

Tvdb is closed source. As for jellyseerr, there's nothing we can really do to solve the discrepancies between the two db's (tmdb and tvdb) since they don't really follow a standard or have episode IDs.

For a fix, you could add the tvdbid into that series, but the problem would be then for people with sonarr, it will just monitor adventure time even when you request distant lands because that's regarded as a special episode by tvdb. Similar thing happens with animaniacs where the reboot is treated as a new season to the old show by tvdb but tmdb treats it as two different shows. Same with groot. Tvdb treats groot as a series, tmdb treats each episode as a mini movie.

**Comment by mo-st** [comment]
Thank you so much for the detailed explanation! Seems like this is not something in the control of jellyseerr then. If I understand correctly, would it be possible to let the user give a preference as to which metadata provider should be considered, as is the case with jellyfin itself if I'm not mistaken? So just ignoring the other one, as in a local preference setting to not mess up other people's setup with sonarr?

**Comment by Fallenbagel** [comment]
> Thank you so much for the detailed explanation! Seems like this is not something in the control of jellyseerr then. If I understand correctly, would it be possible to let the user give a preference as to which metadata provider should be considered, as is the case with jellyfin itself if I'm not mistaken? So just ignoring the other one, as in a local preference setting to not mess up other people's setup with sonarr?

That's also not possible unfortunately. Tmdb is an open source free database therefore we use tmdb. Tvdb is closed source and paid (jellyfin org has some kind of grandfathered small payment agreement or something so they have the tvdb plugin). 

We get the tvdbid so it can be matched for sonarr through tmdb. If you go to any series you'll see that externalids tvdb. However, distant lands didn't work because it wouldn't have an externalid (it used to) because that as a series doesn't exist on tvdb 😔

It's quite a shame that these db's doesn't have a standard they follow 😔

**Comment by mo-st** [comment]
I see, how unfortunate! But I understand it a bit better now, so thank you for that and your time as well!
