### ISSUE TITLE
UI doesn't consider "Local Sign-In" when disabled for certain features

### ISSUE THREAD

**Issue by Jacouille** [Fallenbagel/jellyseerr#825]
### Description

Some features in the UI do not consider the "Local Sign-In" settings when it is disabled.

- In the user list, the "Create Local User" button is shown when setting is disabled.
  - We should hide the button when the setting is disabled
- In the user profile settings (/users/:userId/settings), the email is required. This was added in #803 but does not check the setting. 
  - The email should not be required when the setting is disabled
- The Password tab in the user profile settings (/users/:userId/settings) is shown. The password in that tab is the password for "Local users".
  - We should hide the tab when the setting is disabled

### Version

1.9.2

### Steps to Reproduce

1. Go to the Jellyseerr setting page in the users tab (/settings/users)
2. Disable the "Local Sign-In" setting and save your changes
3. View the issues described in the description section above behave like the setting is still enabled

### Platform

desktop

### Device

all

### Operating System

all

### Browser

all

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
1. Whether you disable local sign in or not, every account is both. Every jellyfin user also is a local account. It's linked

2. Email will be required. We will remove the validation so Email can be jellyfin username/email (it was supposed to be this way but accidental)

3. Refer back to 1. Every user is still a local user  (it's all interlinked) which is why we don't hide these settings

**Comment by gauthier-th** [comment]
Should be fixed by #900
