### ISSUE TITLE
[Feature Request] Automatically purge media that has been deleted from jellyfin

### ISSUE THREAD

**Issue by oskarslusitis** [Fallenbagel/jellyseerr#84]
#### Description

Previously available, but now deleted movies from Jellyfin still shows as available in Jellyseer. You have to manually use option on Jellyseer to delete all data to remove that status. This bug messes up requests, for example I've seen said movie, deleted it, but someone else wants to see it after some time, it shows on Jellyseer as avalable, presses "Play on Jellyfin", it attempts to open the link and it hangs on Jellyfin loading screen. And while it shows as available, it's not possible to request it again. Admin needs to manually clear data for that movie.

#### Version

Jellyseer v1.0.2, docker image
Jellyfin v10.7.7, official docker image

#### Steps to Reproduce

Set up Jellyseer with Jellyfin.
Movies synced, available movies on your Jellyfin show up as Available on Jellyseer.
1. Delete movie on Jellyfin
2. That same movie still shows up on Jellyseer as available.

#### Expected Behavior

Previously available and now deleted movie on Jellyfin, is not available on Jellyseer and users can request it again.

#### Screenshots

not necessary. 

#### Device

-all devices

**Comment by Jpkribs** [comment]
While definitely an issue, I get this same interaction on Overseerr as well. I think the data only goes one direction from Media Sever -> Over/Jellyseer?

**Comment by oskarslusitis** [comment]
If it's the same in Overseer, this should be moved to Feature request. :( 
Is it the same on Ombi (I haven't tried Ombi)? Somehow seemed obvious functionality.

**Comment by Jpkribs** [comment]
Just did a test for that. For me, Ombi experiences the same issue. It looks like Ombi’s solution to this issue is an option in the Media Server configuration for “Clear Data & Resync”. So the benefit there would be that you can mass-clear all missing Movies/Shows but it still appears to be manual.

I’ll have to wait for the Cron tasks in Ombi because they could have that automated but from first check it looks like it’s a manual step.

**Comment by Jpkribs** [comment]
Ombi after all Cron tasks is still showing the deleted movie. After I use “Clear Data & Resync” the movie finally goes away as “Available.” I’m not familiar with what’s going on in the backend but I **THINK** Jellyfin/Emby/Plex has a webhook/endpoint (I’ll call it an endpoint moving forward) for new content but there isn’t an endpoint for deleted content. So the only route to stay up to date for removed content is to delete your cached information and re-call the Media Server to get all of the content again. It would result in a pretty long query similar to your first set up for Jellyseerr. 

There’s an option in Jellyseerr for “Jellyfin Full Library Scan” but I think that’s just coaching any items that weren’t found as recently added items.

From a Jellyseer perspective that would mean it’d either have to re-query the full Media Server every so often to catch missing content or it could be resolved if Jellyfin/Emby/Plex added an endpoint for removed content. 

It might be cool for a feature request to allow Jellyseerr to clear cache and re-query the Media Server as a job. But for performance reasons it’d be valuable to allow that job to be disabled.

**Comment by oskarslusitis** [comment]
Yes, tested myself, you're correct, Ombi does the same. Will have to think of something, as one don't want to grow immense amount of library and is constantly removing media.

**Comment by Fallenbagel** [comment]
It seems that it's a feature ([#377](https://github.com/sct/overseerr/issues/377)) not present in the core Overseerr too. For now our main focus is to simply add Jellyfin/Emby/Plex support to Jellyseerr and update to the latest features of Overseerr (the `:develop` tag)

**Comment by butts136** [comment]
I can see as TO DO in the version 1.2.0 but it is done ?
Can't find this option
Thanks

**Comment by some-random-sperg** [comment]
Hi 

I've been running into this issue as well due to limited space 

I'm afraid i'm not a dev so can't really help on the technical side, i did have a suggestion for how this functionality could be added (i'd imagine) relatively easily. 

The whole point of the app is that it's a slick request system baked into Radarr / Sonarr ..... So why not pickup deleted media notifications from there instead of from Jellyfin? 

 You can already use it to trigger library rescans when content gets added / removed on the "connections" tab. 
While it doesn't look like it has a "baked in" option for Ombi or Overseer at present, it does have dealers choice of a webhook or custom script  that could be leveraged https://imgur.com/a/8jrcGgw 

As far as i can tell the only downside is it **might** only work with monitored content (I've not tested but i'd imagine so), not to mention there's some potential things could drift out of sync over time if it misses a notification for whatever reason etc 

I appreciate ideas are like assholes in that everyone has one and thinks theirs alone doesn't stink but even if it was a less than "perfect" solution... Barring some way to get the notifications out of Jellyfin itself, or embarking on frequent cache purges - I could see this solving the problem at least for "most people, most of the time" sufficiently to make total rebuilds something you'd do a couple of times a year, rather than a couple of times a month.

**Comment by hrenard** [comment]
sct/overseerr#3219 was just merged! :wink:

**Comment by amaank404** [comment]
I can assure you that this is one of those features that I desperately need.

**Comment by amaank404** [comment]
For now, I just clear the database manually using sqlite and let it rerun the scan. Maybe an option to do that as a quick workaround should be present in experimental ui? Just saying

**Comment by Fallenbagel** [comment]
> I can assure you that this is one of those features that I desperately need.

This feature is already there. In the codebase. Just needs to be reworked to support jellyfin/emby

**Comment by amaank404** [comment]
ohhkayz, good luck.

**Comment by Fallenbagel** [comment]
> ohhkayz, good luck but as of now what should I manually delete in the database to clear the list.

I think it'd be better to make use of the api. You can find it in http://jellyseerrip:5055/api-docs
You can find the endpoint for clearing data from it and you can even use that to make a small script to automate even. So like when you remove sth you could let the script identify what's being removed (sonarr and radarr has notifications for removal) and let the script search for it using the end point and remove.

Just a suggestion ^

**Comment by David-Moreira** [comment]
+1

**Comment by David-Moreira** [comment]
Hey guys, 
I came up with this simple app/api that you can deploy to keep jellyseer synced. 
It has an endpoint to sync deleted movies.
And it has two endpoint to act as webhooks for Radarr/Sonarr Movie/Episode Deleted events.

It's not too elegant, but it's getting the job done for now, at least while we don't get a fix for this.

I'm just sharing in case it helps someone else. I deployed a docker container with it.
https://github.com/David-Moreira/JellyseerrSync
