### ISSUE TITLE
jellyseerr in jellyfin

### ISSUE THREAD

**Issue by Wernouxe** [Fallenbagel/jellyseerr#911]
### Description

Hi, do you think that one day there will be a plugin (with an interface) for Jellyfin?

### Desired Behavior

This would allow users to make requests from the same "site" (without having to go to another site, etc.)
Manage requests from the same site

### Additional Context

One less shortcut :')

### Code of Conduct

- [X] I agree to follow Jellyseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
> Jellyfin can never be associated with **Piracy**, even though it's mainly used to play pirated files.

Jellyseerr doesn't condone nor promote **piracy** either. Jellyseerr is a request management software that is basically just a database. Whatever you do with it, is up to you.

**Comment by Fallenbagel** [comment]
Jellyseerr cannot be a plugin in jellyfin as plugins do not allow the modification of the web ui.

**Comment by CalmSeoul** [comment]
> Jellyseerr cannot be a plugin in jellyfin as plugins do not allow the modification of the web ui.

@fallenbagel 

Based on changes in Jellyfin 12, plugins now have the ability to show search results and change the "more like this" feed. Does this change mean that Seerr results can be shown directly in Jellyfin if there was a plugin, or am I misunderstanding what the release notes are saying? Any chance this could be looked at again based on this change? 

https://jellyfin.org/posts/jellyfin-release-12.0/
"Where "more like this" and the suggestion rows get their ideas from is no longer fixed. You now choose the source per library in the same place you already pick metadata providers, so you can use one source for movies and a different one for music.
Search works the same way now: a plugin can add its own results alongside Jellyfin's own. If you have ever wanted Jellyfin to search somewhere else at the same time, that is a plugin now rather than a fork. Both systems are written up for plugin authors in the release notes."
