### ISSUE TITLE
[Feature Request] Manage tags better

### ISSUE THREAD

**Issue by schklom** [Fallenbagel/jellyseerr#93]
#### Description

Only the Admin can set Radarr/Sonarr tags on a request, and it can only be done manually after a user submits a request.

#### Desired Behavior

Admin should be able to give a set of available tags to each user, and the user should be able to choose which ones they want to use by default and adjust for each request.

PS: thank you so much, this service is fantastic :)

**Comment by Fallenbagel** [comment]
This is more of a core overseerr feature. For now we are focusing on getting the latest features of overseerr to jellyseerr (which has been completed in the develop tag) so better to open this on their github.

I do like this feature though, but I wonder what the use case could be. Because let's say you have specific profiles for specific tags on sonarr/radarr but wouldn't the user not know about this? So how do they know which tag to choose? 🤔

**Comment by schklom** [comment]
I was thinking that some users may want a certain quality for a movie but not for another. For example, I don't mind watching a movie that just came out in lesser quality, but if they are available in high quality then I don't want the bad quality.

**Comment by schklom** [comment]
Ignore, this is already in the `develop` version.
